baseurl = "https://www.hadriengourle.com/blog/"
languageCode = "en-us"
title = "Hadrien Gourlé's blog"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "go to hadriengourle.com"
    url = "https://www.hadriengourle.com"

[params]
    description = "Hadrien Gourlé's blog, built with blogdown"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    
    customCSS = ["/css/custom.css"]

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "terminal.svg"
    width = 50
    height = 50
    alt = "Logo"

